version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ls
      - ng build --prod
  post_build:
    commands:
      - cp appspec.yml ./dist/QuittanceFront
      - cp -r scripts ./dist/QuittanceFront
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/QuittanceFront